const APP_CONFIG = {

    mensajesPredefinidosPorArea: {
        'colchones': 'Plan de colchones semanales 1950',
        'accesorios': 'Plan de accesorios semanales: [Tu meta aquí]',
        'bases': 'Plan de bases semanales: [Tu meta aquí]',
        'muebles': 'Plan de muebles semanales: [Tu meta aquí]',
        'textil': '',
        'metalurgia': '',
        'fibra': '',
        'espuma': ''
    },

    emailMap: {
        colchones: 'joseluisduran9814@gmail.com',
        accesorios: 'joseluisduran9814@gmail.com',
        bases: 'joseluisduran9814@gmail.com',
        muebles: 'victor.cortes@rosen.cl',
        textil: 'joseluisduran9814@gmail.com',
        metalurgia: 'joseluisduran9814@gmail.com',
        fibra: 'joseluisduran9814@gmail.com',
        espuma: 'joseluisduran9814@gmail.com'
    },

    configuracionDeVisibilidad: {
        'colchones': {
            cumplimiento: true,
            colchonesProd: true,
            datosRelevante: true,
            sucesos: true,
            porcAusentismo: true,
            ausentismo: true,
            horasExtra: true,
            gestionesMejora: true,
            accesoriosPlan: false,
            basesPlan: false,
            mueblesPlan: false,
            fibraScrap: false,
            espumaScrap: false,
        },
        'accesorios': {
            cumplimiento: true,
            accesoriosPlan: true,
            sucesos: true,
            porcAusentismo: true,
            ausentismo: true,
            horasExtra: true,
            gestionesMejora: true,
            colchonesProd: false,
            datosRelevante: false,
            basesPlan: false,
            mueblesPlan: false,
            fibraScrap: false,
            espumaScrap: false,
        },
        'bases': {
            cumplimiento: true,
            basesPlan: true,
            sucesos: true,
            porcAusentismo: true,
            ausentismo: true,
            horasExtra: true,
            gestionesMejora: true,
            colchonesProd: false,
            datosRelevante: false,
            accesoriosPlan: false,
            mueblesPlan: false,
            fibraScrap: false,
            espumaScrap: false,
        },
        'muebles': {
            cumplimiento: true,
            mueblesPlan: true,
            sucesos: true,
            porcAusentismo: true,
            ausentismo: true,
            horasExtra: true,
            gestionesMejora: true,
            colchonesProd: false,
            datosRelevante: false,
            accesoriosPlan: false,
            basesPlan: false,
            fibraScrap: false,
            espumaScrap: false,
        },
        'textil': {
            sucesos: true,
            horasExtra: true,
            gestionesMejora: true,
            porcAusentismo: true,
            ausentismo: true,
            cumplimiento: false,
            colchonesProd: false,
            datosRelevante: false,
            accesoriosPlan: false,
            basesPlan: false,
            mueblesPlan: false,
            fibraScrap: false,
            espumaScrap: false,
        },
        'metalurgia': {
            sucesos: true,
            porcAusentismo: true,
            ausentismo: true,
            horasExtra: true,
            gestionesMejora: true,
            cumplimiento: false,
            colchonesProd: false,
            datosRelevante: false,
            accesoriosPlan: false,
            basesPlan: false,
            mueblesPlan: false,
            fibraScrap: false,
            espumaScrap: false,
        },
        'fibra': {
            fibraScrap: true,
            sucesos: true,
            porcAusentismo: true,
            ausentismo: true,
            horasExtra: true,
            gestionesMejora: true,
            cumplimiento: false,
            colchonesProd: false,
            datosRelevante: false,
            accesoriosPlan: false,
            basesPlan: false,
            mueblesPlan: false,
            espumaScrap: false,
        },
        'espuma': {
            espumaScrap: true,
            sucesos: true,
            porcAusentismo: true,
            ausentismo: true,
            horasExtra: true,
            gestionesMejora: true,
            cumplimiento: false,
            colchonesProd: false,
            datosRelevante: false,
            accesoriosPlan: false,
            basesPlan: false,
            mueblesPlan: false,
            fibraScrap: false,
        }
    },

    textMappings: {
        "title-colchones-prod": ["Colchones Producción Del Día", "Colchones Producción De La Semana"],
        "title-accesorios-plan": ["Plan Diario y Pendientes Día Anterior", "Plan Semanal y Pendientes Semana Anterior"],
        "title-bases-plan": ["Plan Diario y Pendientes Día Anterior", "Plan Semanal y Pendientes Semana Anterior"],
        "title-muebles-plan": ["Plan Diario y Pendientes Día Anterior", "Plan Semanal y Pendientes Semana Anterior"],
        "label-cumplimiento": ["Porcentaje De Cumplimiento Día Anterior:", "Porcentaje De Cumplimiento Semana Anterior:"],
        "label-colchones-plan": ["Plan Del Día", "Plan De La Semana"],
        "label-colchones-producido": ["Producido", "Producido Semanal"],
        "label-accgen-plan": ["Plan Del Día Accesorio", "Plan De La Semana Accesorio"],
        "label-accgen-prod": ["Producido Accesorios", "Producido Semanal Accesorios"],
        "label-accplum-plan": ["Plan Del Día Plumones", "Plan De La semana Plumones"],
        "label-accplum-prod": ["Producido Plumones", "Producido Semanal Plumones"],
        "label-accalm-plan": ["Plan Del Día Almohadas", "Plan De La Semana Almohadas"],
        "label-accalm-prod": ["Producido Almohadas", "Producido Semanal Almohadas"],
        "label-bases-plan": ["Plan Del Día", "Plan De La Semana"],
        "label-bases-prod": ["Producido", "Producido Semanal"],
        "label-muebsofa-plan": ["Plan Del Día Sofás", "Plan De La Semana Sofás"],
        "label-muebsofa-prod": ["Sofás Producido", "Sofás Producido Semanal"],
        "label-muebrecl-plan": ["Plan Del Día Reclinables", "Plan De La Semana Reclinables"],
        "label-muebrecl-prod": ["Reclinables Producidos", "Reclinables Producidos Semanal"],
        "label-muebresp-plan": ["Plan Del Día Respaldos u Otros", "Plan De La Semana Respaldos u Otros"],
        "label-muebresp-prod": ["Respaldo u Otros Producido", "Respaldo u Otros Producido Semanal"],
    },

    subAreaMappings: {
        colchones: ["Cerrado", "Emsamblaje", "Vulcanizado", "Otra Area"],
        accesorios: ["Accesorio Área 1", "Accesorio Área 2", "Otro Accesorio"],
        bases: ["Tapizado Convencional", "Tapizado Funcional ", "Funda", "Clavado De Parrilla"],
        muebles: ["Corte", "Confección", "Pegado de Cojines", "Llenado", "Armado Estructura", "Tapizado", "Embalaje", "Celula Reclinables"],
        textil: ["Multiaguja", "Uniaguja", "Encintado","Confección Fuelle","Area General"],
        metalurgia: ["Boney", "Cosisoft", "Pocket", "Area General"],
        fibra: ["Masia 1", "Masia 2", "Masia 3", "Masia 4", "Deshilachado", "Area General"],
        espuma: ["Espuma Área 1", "Espuma Área 2", "Otro Espuma"]
    },

    tipoIncidenteOptions: [
        "Falla De Maquina", "Producto Con Falla", "Producto Pendiente","Planificación", "Por Personal", "Seguridad", "Gestion De Mejora", "Otro Problema"
    ],

    areaResponsableOptions: [
        "Bases", "Ensamblado Colchon", "Espuma", "Fibra", "Materia Prima","Mueble", "Proveedor", "Textil Accesorio", "Textil Colchon", "Mantención","Otra Area Responsable", "Sin Responsable"
    ],
    maquinaFallaMappings: {
        'T. Bonn. Huajian': ['2085', '2087', '2209', '1597', '2086', '2208', '2383', '2086', '2384'],
        'P. Bonnell': ['1546'],
        'T. Bonn. Spuhl': ['0813','2001'],
        'T. Bonn. Fides': ['2171'],
        'T. Cosiflex': ['0029'],
        'Espiralera Rosen': ['1412'],
        'T. Cosisoft Huajian': ['2922'],
        'T. Cosisoft Spuhl': ['0661'],
        'E Pocket Springform': ['2221'],
        'E. Pocket Huajian': ['2668', '2808', '2915','2386'],
        'Embalado Parrillas': ['2321']
    },
    tipoFallaMaquinaOptions: [
        "electrica", "mecanica", "configuracion", "otro"
    ],
};
